environment:
  machine_user: test_user
  machine_pass: Pass@word1
  machine_port: 5985
  KITCHEN_YAML: .kitchen.appveyor.yml

cache:
  - '%TEMP%\verifier\gems'

install:
  - cinst chefdk
  - SET PATH=C:\opscode\chefdk\bin;%PATH%

build_script:
  - chef exec bundle install --without=development integration
  - copy .kitchen.appveyor.yml .kitchen.local.yml

test_script:
  - chef exec kitchen test
